[package]
name = "comphdl-02"
version = "0.1.0"
authors = ["Badel2 <2badel2@gmail.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.15.2"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
vcd = "0.3"
lalrpop-util = "0.15.2"
regex = "0.2.1"
